import { PartitionKeyUUID } from '../../src/decorator/impl/key/partition-key-uuid.decorator'
import { Model } from '../../src/decorator/impl/model/model.decorator'

@Model()
export class ModelWithAutogeneratedId {
  @PartitionKeyUUID()
  id: string
}
