import { Model } from '../../src/decorator/model.decorator'
import { PartitionKeyUUID } from '../../src/decorator/partition-key-uuid.decorator'

@Model()
export class ModelWithAutogeneratedId {
  @PartitionKeyUUID() id: string
}
