name: Lint, Test, Build and optionally Publish

on:
  # push only for branches (ignore tags)
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    # pull request only for branches (ignore tags)
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  test:
    strategy:
      matrix:
        node:
          - 22
          - 24
          - 25
    name: Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup Node and NPM Cache
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}
      - name: Install
        run: HUSKY=0 npm ci
      - name: Test
        run: npm run test:ci
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Setup Node and NPM Cache
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f #v6.3.0
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install
        run: HUSKY=0 npm ci
      - name: Lint
        run: npm run lint:ci
      - name: Build
        run: npm run build
        env:
          CI: true
      # report coverage only for non PR
      - name: coveralls
        if: ${{ startsWith(github.ref, 'refs/pull/') == false }}
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # publish to latest if on master branch
      - name: release master
        if: ${{ github.ref == 'master' }}
        run: |
          npm run docs:build
          npx semantic-release
          npm run docs:deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # publish pre-release if non master branch and allowed by .releaserc.yml configuration (only for non-PR branches)
      - name: release non-master version
        if: ${{ github.ref != 'master' && startsWith(github.ref, 'refs/pull/') == false }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
